language: node_js
node_js:
- '14'
dist: trusty
sudo: required
addons:
  sonarcloud:
    organization: jeongahyi
    token:
      secure: 7e5cbe989ed9c2f4577b0c91e188e70aca7262e3
branches:
  only:
  - master
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
# before_script:
# - npm install -g @angular/cli
# - npm install -g firebase-tools
script:
- npm run test -- --watch=false
after_success:
- ng build --prod
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: DDPwFCuSqIq1n5FSO+54RdqWicIF9NAB5HG91UgH5zDDzr6SvKHiTlPksVkQ2y0JucOCdbUvPTHNVRAIifPA/gZ6AesXEIeviNcXETTY9ZfGBu8MfGk0mZUjxnOJ27RSy9amIM8XD2B4ES/gCeD6fmoNt0gvCkLKYHIJ1bhMfi+Aph3wVVtLqcdGszpmK4ekZ281JfgDcMq2EcLLZOtXmc0rIu84pr/3RxE22SOo0d0syrDkhmn01TRvAiMTSwnc/fjg7/T+Wn1cUia3fkD+Lgakq9ljfrD/Md/ahQyC5sa0GRBHyWa0EJooUlapus8oLAnOgdVh48+cV+Ak16olc63k9emRsb1sEgJXiG0S/CjtHDmL5+2Ne5t3v8Ld+FhaqQZKLMucsKSAU1xT553rtlghELRw/g0DJFzcAD1OcUw/f3sBJ9c0vygtLMz/WLgWFACU7d2f5akXfqNlD0TJdXaCwF8K8XSZiDCtw1GZwvLiZ93nMM/4C4MdC7ABOCQQQjhvQ7KXbzhg9ExTWD1PHewSMw8vixvsgL3YqY6pYjtiUOb4xvfSmypG1RAj6GDdIiyb2EajdPX79b/pGiDv+CvAdFSGzYsV+z8RhGRFKxAdp3d7+WT/Zm+Y2Z4uBmJAPuQLTbvKoLq4v+I11lvmbQv15J9F0lVMu7jYf/AJliE=
